Add extended options, update UI
ITS-Digital-Technology/global-elements-wordpress pull request #7
Opened 2024-12-20 21:59 UTC by raymondkingston

Extended options with:

- show/hide wordmark
- show/hide 'explore nu' menu
- enter skip link selector value

Also updated UI a little bit.

2024-12-23 15:31 UTC, CeeRoo approved these changes
Approve-iddly-ooved! Just FYI, there's a commented out section in nu_global_elements.php from line 37 to 59, but maybe that was just to keep a historical reference in the file.

2024-12-23 15:44 UTC, raymondkingston commented
> Approve-iddly-ooved! Just FYI, there's a commented out section in nu_global_elements.php from line 37 to 59, but maybe that was just to keep a historical reference in the file.

Thanks, Chris! Good catch. Just updated with some housekeeping.

2024-12-23 18:32 UTC, cam-vanorman requested changes
Small change that Chris mentioned, otherwise this looks great! Thanks Ray!

2024-12-23 18:32 UTC, cam-vanorman commented on nu_global_elements.php
> +        );
Once this is updated/removed, happy to approve the PR.

2025-01-03 02:28 UTC, cam-vanorman approved these changes

2025-01-06 20:19 UTC, merged

2025-01-06 20:43 UTC, kenwilliams-nu reviewed
Awesome, job, Ray!